services:
  - type: web
    name: restoran-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:create_app() -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: ADMIN_GROUP
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant_db
          property: connectionString

databases:
  - name: restaurant_db
    plan: basic-1gb